### ISSUE TITLE
Project type not highlighted in New Project menu

### ISSUE THREAD

**Issue by vgalaktionov** [jontaydev/monokai-pro-jetbrains#1]
Hi there, 

First of all, thanks for the great theme! I have been looking for a port of Monokai Pro to the Intellij products for ages.

I have found a small issue with the theme: in the New Project menu (at least in Pycharm), the currently selected project type is not highlighted like it is in the native theme. This makes it impossible to see what the current type is, except by guessing from the available settings. See attached screenshot for an example.

<img width="771" alt="Screenshot 2020-02-03 at 19 36 32" src="https://user-images.githubusercontent.com/12257510/73680435-8822cf00-46bc-11ea-9743-3068a4c1d7ee.png">

Any ideas how I could help resolve this?

**Comment by jontaydev** [comment]
Thanks for pointing this out, I can see it as well. I'm guessing the issue is from here: https://github.com/jontaydev/monokai-pro-jetbrains/blob/master/src/Monokai%20Pro.theme.json#L659

I may adjust the sidebar here to match the project view (darker color). I'll take a look tonight.

**Comment by jontaydev** [comment]
Fixed and submitted 0.2 to the plugin repository, along with a few other small fixes.

<img width="889" alt="Screen Shot 2020-02-03 at 9 49 19 PM" src="https://user-images.githubusercontent.com/2243530/73709431-11db9800-46cf-11ea-8ff9-07f9dd759155.png">

**Comment by vgalaktionov** [comment]
Awesome, thanks for the quick response!
