### ISSUE TITLE
Change background color of selected menu item

### ISSUE THREAD

**Issue by pyriand3r** [jontaydev/monokai-pro-jetbrains#2]
Hi,
first thanks for the great work. It is great to have Monokai Pro in Intellij Idea! But there is a single thing i would request to change (or maybe it is only a bug in my ide).

There is no difference in the background color of the menu items and the current selected menu item. As i am using mainly the keyboard to navigate in the menus it is impossible for me to determine on which entry i am because there is no visual indicator...

It would be great if you could highlight the current selected menu item.

**Comment by jontaydev** [comment]
Are you talking about the top-level menubar (File, Edit, View, etc)?

I'm a Mac user, so those colors are controlled by the OS. If your seeing issues though, maybe I can fire up a VM and try to reproduce this.

**Comment by pyriand3r** [comment]
Hi,
yes I am talking about that top-level menubar. I'm on Arch Linux with the i3 desktop manager and there is no difference between normal and highlighted menubar item.

**Comment by jontaydev** [comment]
Ok thanks, I'll take a look if not tonight this weekend.

**Comment by nikitabuyevich** [comment]
Same issue. Would be great if you could fix it

**Comment by nikitabuyevich** [comment]
Fixed the issue in [my fork](https://github.com/nikitabuyevich/monokai-pro-forked-jetbrains). Feel free to pull the changes.

**Comment by jontaydev** [comment]
Pulled in fixes from @nikitabuyevich

**Comment by pyriand3r** [comment]
Fixed :+1:
