### ISSUE TITLE
Feature Request: Same Icons as Material UI Lite

### ISSUE THREAD

**Issue by handkerchief333** [jontaydev/monokai-pro-jetbrains#4]
This monokai theme is far the best theme out there for Jetbrains.

One thing that could be even better are the icons. The best icons in my opinion has this theme:
https://plugins.jetbrains.com/plugin/12124-material-theme-ui-lite

So the monokai theme together with these icons... Believe me that would be awesome.

**Comment by handkerchief333** [comment]
Ok that one was easy :)
https://www.material-theme.com/docs/configuration/icons-settings/

So I think you don't have to change anything :)

**Comment by jontaydev** [comment]
Thanks, I would only add icons to the plugin if I can get the official Monokai Pro icons from the original author. Which is probably unlikely, since its a paid plugin on VSCode/Sublime.
