### ISSUE TITLE
No underline for selected files

### ISSUE THREAD

**Issue by nikitabuyevich** [jontaydev/monokai-pro-jetbrains#5]
![image](https://user-images.githubusercontent.com/10747974/79673927-d61b7f00-81a3-11ea-8300-e0996de8d5cc.png)

Here's an example taken from a different theme. This theme does not have underlines or any indications to let you know which file you currently have open.

Tested with Windows 10.

**Comment by nikitabuyevich** [comment]
Fixed the issue in [my fork](https://github.com/nikitabuyevich/monokai-pro-forked-jetbrains). Feel free to pull the changes.

**Comment by jontaydev** [comment]
Thanks for making these changes, I'm reviewing now. 

The only thing I'm noticing so far is the font looks extremely large (18) on my MacBook with default resolution and scaling. I can check what most themes are using but I forked from the Material theme which uses 12.

I like using a color variable for yellow, but I would like to be consistent and have all primary colors use variables. I may update later.

**Comment by jontaydev** [comment]
Also FYI, feel free to do a proper fork/pull request in the future, it would make it much easier to review, and also keep you credited in the git history.

Or was there a reason you wanted a separate published plugin on the JetBrains repository, vs pulling into this one?

**Comment by jontaydev** [comment]
The only other thing is I probably want to change is the tearline color you picked. I would rather match how VSCode looks, but I'm not sure if its possible:

<img width="614" alt="Screen Shot 2020-04-25 at 3 04 58 PM" src="https://user-images.githubusercontent.com/2243530/80288463-2b0c4780-8706-11ea-969f-06ca155caca6.png">

**Comment by nikitabuyevich** [comment]
> Thanks for making these changes, I'm reviewing now.
> 
> The only thing I'm noticing so far is the font looks extremely large (18) on my MacBook with default resolution and scaling. I can check what most themes are using but I forked from the Material theme which uses 12.
> 
> I like using a color variable for yellow, but I would like to be consistent and have all primary colors use variables. I may update later.

Updated the font size to 12 and added variables for all colors used.

> Also FYI, feel free to do a proper fork/pull request in the future, it would make it much easier to review, and also keep you credited in the git history.
> 
> Or was there a reason you wanted a separate published plugin on the JetBrains repository, vs pulling into this one?

I've made some modifications to the theme that you might not agree with so I thought it would be easier to just fork my own. e.g., I've changed the `identifier under caret` to have a bordered effect instead of highlighting the background since JetBrains doesn't support opacity and I couldn't find a consistent color that was clear.

> The only other thing is I probably want to change is the tearline color you picked. I would rather match how VSCode looks, but I'm not sure if its possible:
> 
> <img alt="Screen Shot 2020-04-25 at 3 04 58 PM" width="614" src="https://user-images.githubusercontent.com/2243530/80288463-2b0c4780-8706-11ea-969f-06ca155caca6.png">

The tearline color that VSCode uses is much brighter than the one I selected since VSCode by defaults hides the tearline unless you're hovering over it. I've updated mine just now to be darker and highlight to a whiter color on selection.

**Comment by jontaydev** [comment]
The caret identifier change looks good. 

I pushed up your changes to my repo, but only adjusted the tearline slightly (`403e41`). I want to think about the tearline a bit more, and will probably look at that again later. Ideally, I want to have no line for the top-level code sections like VSCode. That brighter color only shows up when its selected.

I'm going to review one more time tonight, and will push up a new version to the JetBrains repository if everything looks good.

Thanks for your help!

**Comment by nikitabuyevich** [comment]
> The caret identifier change looks good.
> 
> I pushed up your changes to my repo, but only adjusted the tearline slightly (`403e41`). I want to think about the tearline a bit more, and will probably look at that again later. Ideally, I want to have no line for the top-level code sections like VSCode. That brighter color only shows up when its selected.
> 
> I'm going to review one more time tonight, and will push up a new version to the JetBrains repository if everything looks good.
> 
> Thanks for your help!

👍 Thanks and nice job on converting the theme.
