### ISSUE TITLE
Selected unused variable cannot readable on Java

### ISSUE THREAD

**Issue by validatedev** [jontaydev/monokai-pro-jetbrains#6]
As you can see in the screen recording and screenshot, I cannot see what variable is this when clicked on unused variable.

[video.zip](https://github.com/jontaydev/monokai-pro-jetbrains/files/4512782/video.zip)
![image](https://user-images.githubusercontent.com/29679552/79918083-6b34a700-8434-11ea-94d1-af848ad4bc18.png)

**Comment by nikitabuyevich** [comment]
Fixed the issue in [my fork](https://github.com/nikitabuyevich/monokai-pro-forked-jetbrains). Feel free to pull the changes.

**Comment by jontaydev** [comment]
Pulled in fixes from @nikitabuyevich

**Comment by jontaydev** [comment]
Gonna close this, but let me know if your still seeing any issues. Thanks
